### ISSUE TITLE
pipeline use?

### ISSUE THREAD

**Issue by luckman212** [RealAlexandreAI/json-repair#16] opened 2024-06-29 17:18 UTC
I'm using Darwin arm64 binary downloaded from releases on macOS 14.5 (it self-reports as v0.0.8)

I was hoping to use the CLI in a shell pipeline.

When I tried

```
$ echo "{'employees':['John', 'Anna', " | jsonrepair -f /dev/stdin
```

I get the somewhat unexplainable output below:
```
{}
---
{"employees":["John","Anna"]}
```

What is the `---` and extra null output `{}` above it?

I notice that this seems to work though:

```
$ echo "{'employees':['John', 'Anna', " | jsonrepair -i "$(</dev/stdin)"
{"employees":["John","Anna"]}
```

**Comment by luckman212** [comment] 2024-06-29 17:27
I looked at the source, seems like this is where it's coming from:

https://github.com/RealAlexandreAI/json-repair/blob/3cc8f746d3d97d5761c09fd020abd27c46635545/cli/jsonrepair-cli.go#L59-L63

It seems to think that there's both file (-f) and input (-i) being supplied, when in fact there isn't. I even get that kind of result with e.g.

```
$ echo "{ foo: 1 }" >test.json
$ jsonrepair -f test.json
{}
---
{"foo":1}
```

But, always passing `-i ''` gets rid of it.
```
$ jsonrepair -f bad.json -i ''
{"foo":1}
```
Is this expected behavior?

**Comment by RealAlexandreAI** [comment] 2024-07-02 03:00
I will adjust to a better strategy at an appropriate time after work, and add automated unit tests for the pipeline use scenario.

**Comment by RealAlexandreAI** [comment] 2024-07-13 09:33
fixed in 0.0.11.

**Comment by luckman212** [comment] 2024-07-15 13:14
@RealAlexandreAI Thank you for taking the time, but, am I crazy or is this still a little broken?

```
$ jsonrepair -v
Version: 0.0.11

$ echo "{ foo: 1 }" >test.json

$ jsonrepair -f test.json
{}

$ jsonrepair -i '' -f test.json
{"foo":1}
```

Why does `jsonrepair -f test.json` return no output?

**Comment by RealAlexandreAI** [comment] 2024-07-16 07:04
Sorry for this matter. I made a simple repair during the weekend. 
Now I have made a new release 0.0.13 and added relatively comprehensive unit tests. 
The root cause of the problem is due to the incorrect initial value of '-i'.  

I will keep this issue open until you verify all of your scenarios.

**Comment by luckman212** [comment] 2024-07-16 11:46
0.0.13 LGTM! Thanks for digging into it. This is an amazing tool!

**Closed** 2024-07-17 03:24 UTC
Labels: bug
